baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Full Stack Observability Labs"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "true"
uglyurls = "true"
enableEmoji = true

[params]
# Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
# Useful to give opportunity to people to create merge request for your doc.
# See the config.toml file from this documentation site to have an example.
#editURL = ""
# Author of the site, will be used in meta information
author = "Wayne Brown"
# Description of the site, will be used in meta information
description = "Cisco Full Stack Observability Labs"
# Shows a checkmark for visited pages on the menu
showVisitedLinks = true
# Disable search function. It will hide search bar
disableSearch = false
# Javascript and CSS cache are automatically busted when new version of site is generated. 
# Set this to true to disable this behavior (some proxies don't handle well this optimization)
disableAssetsBusting = false
# Set this to true to disable copy-to-clipboard button for inline code.
disableInlineCopyToClipBoard = false
# A title for shortcuts in menu is set by default. Set this to true to disable it. 
disableShortcutsTitle = false
# When using mulitlingual website, disable the switch language button.
disableLanguageSwitchingButton = true
# Hide breadcrumbs in the header and only show the current page title
disableBreadcrumb = false
# Hide Next and Previous page buttons normally displayed full height beside content
disableNextPrev = false
# Order sections in menu by "weight" or "title". Default to "weight"
ordersectionsby = "weight"
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "mine"
# AppDynamics EUM application key
#eumAppKey = "AD-AAB-ABB-FZP"
# AppDynamics EUM version
#eumVersion = "20.9.0.3268"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
name = "<i class='fas fa-graduation-cap'></i> AppDynamics Documentation"
url = "https://docs.appdynamics.com"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-graduation-cap'></i> ThousandEyes Documentation"
url = "https://docs.thousandeyes.com/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-graduation-cap'></i> Intersight Documentation"
url = "https://intersight.com/help/getting_started"
weight = 12

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = true

[deployment]
order = [".jpg$", ".gif$", ".png$"]
 
[[deployment.targets]]
name = "aws-s3"

# !!! PER LITE VS FULL START !!!

# FULL
#URL = "s3://performance-fso-labs-static-site-tem-s3bucketroot-5do5jor261fm?region=us-east-1"
#cloudFrontDistributionID = "E2J019Z1QMEF6L"

# LITE
#URL = "s3://lt-performance-fsolabs-net-static-si-s3bucketroot-xgbjrok3tmw0?region=us-east-1"
#cloudFrontDistributionID = "E272YEQOMTGATX"

# !!! PER LITE VS FULL END !!!

 
[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true
 
[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false
 
[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true
 
[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true